### ISSUE TITLE
Running a command in terminal does not save to terminal's history

### ISSUE THREAD

**Issue by johngraham262** [kortina/run-in-terminal#2]
There is a space at the beginning of the command that gets sent to terminal. That space causes the command to not get saved in the terminal's history.

**Comment by mrcasals** [comment]
See #37 for a PR implementing this.

**Comment by mrcasals** [comment]
As a patch until #37 is merged, I run `unset HISTCONTROL` in my Linux machine to keep space-starting commands in the history. Of course, this means that _any_ command starting with a space will be kept in the history, so this might not be a valid solution to everyone. 

If you're on a Mac, then you won't probably need the command, since `HISTCONTROL` is already unset there by default.
